POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "Jordan Peterson is the painful drug which is necessary",
    "important" : true
}
###
DELETE http://localhost:3001/api/notes/63f473a9a4e60416795083d6
###
POST http://localhost:3001/kyabaat
Content-Type: application/json

{
    "content" : "Hey there",
    "title" : "Htfayd"
}

###

PUT http://localhost:3001/api/notes/63f474d335e42a0a58b7912a
Content-Type: application/json

{
    "content" : "Jordan Peterson is the painful drug which is asbolutely necessary",
    "important" : true
}